<?php

namespace ShopBundle\Repository;

/**
 * MerchandiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerchandiseRepository extends \Doctrine\ORM\EntityRepository
{
}
